

services:
  db:
    image: mariadb
    container_name: db
    restart: always
    environment:
      MYSQL_DATABASE: mysql
      MYSQL_ROOT_PASSWORD: Password

    expose:
      - 3306
    volumes:
      - /opt/db:/var/lib/mysql
      - /opt/schema.sql:/docker-entrypoint-initdb.d/init.sql

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - 80:80
    volumes:
    - /opt/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro



  flask:
    image: snickch/flask001:v2
    container_name: flask
    restart: always
    expose:
        - 5000
    volumes:
      - ./app:/app:ro
    command: gunicorn -w 4 --bind 0.0.0.0:5000 wsgi:app
    depends_on:
      - "db"

  portainer:
    container_name: portainer
    image: portainer/portainer-ce
    restart: always
    ports:
      - "9000:9000/tcp"
    environment:
      - TZ=Europe/Zurich
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/portainer:/data
     